### ISSUE TITLE
[Bug]: RabbitMQ 8.x.x chart unavailable

### ISSUE THREAD

**Issue by christianhuening** [finleap-connect/monoskope#161]
**Describe the bug**
The referenced rabbitMQ chart is not available anymore. We need to update the base chart version to at least 9.x.x or already jump to 10.x.x.

Update notes: https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#to-900

This currently leads to failing builds.

**Expected behavior**
RabbitMQ chart is available and builds succeed.

**Comment by jastBytes** [comment]
Has been fixed with #162
