### ISSUE TITLE
Vault Operator link goes to a private gitlab instance

### ISSUE THREAD

**Issue by lewiscowper** [finleap-connect/monoskope#49]
**Describe the bug**
Vault Operator (optional) link on the [deployment doc](https://github.com/finleap-connect/monoskope/blob/main/docs/deployment/README.md) does not resolve to a publicly available repository.

**To Reproduce**
1. Go to '[docs/deployment/README.md](https://github.com/finleap-connect/monoskope/blob/main/docs/deployment/README.md)'
2. Click on 'vault-operator'
3. Don't be logged into gitlab.figo.systems
4. See authentication requirement to see the repository.

**Expected behavior**
I would expect the link to the repository to work.

**Screenshots**
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/593574/152976247-adb061f7-0aa4-4c12-87b2-a2d6f8a926dd.png">

**Additional context**
👋🏻

**Comment by christianhuening** [comment]
Thanks @lewiscowper we're planning to open source the vault operator as well, it just requires some cleaning before.

**Comment by jastBytes** [comment]
Fixed
